services:
  postgres:
    image: postgres:16-alpine
    container_name: medilink-postgres
    restart: always
    env_file: .env.db
    ports:
      - 7671:5432
    volumes:
      - medilink-pgdata:/var/lib/postgresql/data

  app:
    image: aorus22/medilink:latest
    container_name: medilink-app
    restart: always
    env_file: .env
    ports:
      - 7672:3000
      - 7673:5555
    depends_on:
      - postgres

volumes:
  medilink-pgdata:
