services:
  postgres:
    image: postgres:17-alpine
    container_name: medixense-postgres
    restart: always
    environment:
      POSTGRES_DB: medixensedb
      POSTGRES_USER: medixense_user
      POSTGRES_PASSWORD: medixense_password
    ports:
      - 7671:5432
    volumes:
      - medixense-pgdata-v2:/var/lib/postgresql/data

  app:
    build: .
    container_name: medixense-app
    restart: always
    environment:
      DATABASE_URL: "postgresql://medixense_user:medixense_password@postgres:5432/medixensedb?schema=public"
    ports:
      - 7672:3000
      - 7673:5555
    depends_on:
      - postgres

volumes:
  medixense-pgdata-v2:
